<?php

echo $this->form(null, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->openTag($this->form);
$this->form->prepare();

?>
<div class="form-group">

    <?php echo $this->formRow($this->form->get(\Application\Constants\PedidoConst::FLD_ID_PEDIDO)); ?>
    <?php echo $this->formRow($this->form->get(\Application\Constants\PedidoConst::FLD_DESCRICAO)); ?>
    <?php echo $this->formRow($this->form->get(\Application\Constants\PedidoConst::FLD_PRODUTO)); ?>
    <?php echo $this->formRow($this->form->get(\Application\Constants\PedidoConst::FLD_FORNECEDOR)); ?>
    <?php echo $this->formRow($this->form->get(\Application\Constants\PedidoConst::FLD_DATA)); ?>
    <?php echo $this->formRow($this->form->get(\Application\Constants\PedidoConst::FLD_QTD)); ?>
    <?php echo $this->formRow($this->form->get(\Application\Constants\PedidoConst::FLD_UNIDADE)); ?>
</div>

<div class="row botoesacao">
    <?php echo $this->formButton($this->form->get('btn_salvar')); ?>
    <?php echo $this->formButton($this->form->get('btn_cancelar')); ?>

</div>

<?php echo $this->form()->closeTag(); ?>

